[package]
name = "pride-scp-discovery"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
csv.workspace = true
pride-scp-core = { path = "../pride-scp-core" }
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
